Repository jsk-ros-pkg/jsk_roseus, pull requests merged in 2019-12, with the labels that each got.

#615 [roseus_tutotrials] Add euslisp example using hsi_color_filter
  roseus_tutorials/launch/hsi_color_filter.launch
  roseus_tutorials/package.xml
  roseus_tutorials/src/display-bounding-box-array.l
Labels: enhancement

#630 Add command line option to start roseus with gdb
  roseus/bin/roseus.in
Labels: enhancement

#629 add list-param and search-param with test code
  roseus/roseus.cpp
  roseus/test/param-test.l
Labels: PR/MergeOk

#627 [roseus_smach] add code explanation of simple-state-machine in README.md.
  roseus_smach/README.md
Labels: document

#621 Return t after calling service in (call-empty-service service)
  roseus/euslisp/roseus-utils.l
Labels: PR/MergeOk, bug, enhancement

#620 add SoundRequest.volume for kinetic
  roseus/test/say.l
  roseus_tutorials/src/aques-talk.l
  roseus_tutorials/src/vision-action-example1.l
  roseus_tutorials/src/vision-action-example2.l
Labels: PR/MergeOk
