Repository jsk-ros-pkg/jsk_roseus, pull requests merged in 2021-02, with the labels that each got.

#643 fix typo in actionlib.l
  roseus/euslisp/actionlib.l
Labels: PR/MergeOk, bug

#646 add more info on timeout parameter of wait-for-service
  roseus/roseus.cpp
Labels: PR/MergeOk

#645 Fix typo: geoometry -> geometry
  roseus/euslisp/eustf.l
Labels: PR/MergeOk, hacktoberfest-accepted

#642 [roseus] Remove duplicated dependency in package.xml
  roseus/package.xml
Labels: PR/MergeOk
